# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19342bd890df02b7dcf8c354684f30536537ec6ead9f6ded84292acc0370e7951123a8c2a84381aec333984c884c8c835348be61cb49cac850de138057ad8d30

test:
  secret_key_base: f3ae9f4f49f4a9b9d4e62a6a67df29f0e51c426d71db1f78aef3d52855ddd038c8d9f5925065b97ad77fe811db93a49bfdd268927eda31cdf2df39bac4b15815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
